apiVersion: v1
kind: Service
metadata:
  name: workspace-manager
  namespace: workspace-system
spec:
  type: ClusterIP

  selector:
    app: workspace-manager

  ports:
    - name: http
      port: 8000
      targetPort: 8000
